#上传文件路径配置
upload:
  #上传路径s
  file:
    root-path: '@upload.file.root@'
    temp-path: /temp
    formal-path: /formal
    image-path: /image/
    file-path: /file/
    qrimage-path: /qrcode/
  #静态文件路径转发
  mapping:
    image: /image/**
    file: /file/**
    temp-image: /tempImage/**
  #压缩图片
  thumbnail:
    height: 152
    width: 152
    prefix: min