banner:
  charset: utf-8
  location: classpath:banner.txt
#配置总览,控制加载哪个配置文件
spring:
  profiles:
    active: dev
  application:
    name: springBoot
  config:
    location: classpath:filePath/config.yml
