#根
base:
  #Spring security相关配置
  spring:
    security:
      remember:
        key: cqabj
        parameter: _remember_me
        cookie-name: REMEMBER_ME
      admin:
        resources:
          - /cache
          - /admin
          - /management
      #静态资源
      web-ant-matchers:
        - /favicon.ico
        - /druid/**
        - /image/**
        - /tempImage/**
        - /file/**
      #跨域制定域名IP
      csrf:
        enable: true
        execludeUrls:
          - 127.0.0.1
          - localhost